// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (
  is_group, title, created_by
) VALUES (
  $1, $2, $3
)
RETURNING id, is_group, title, created_by, created_at
`

type CreateConversationParams struct {
	IsGroup   bool
	Title     pgtype.Text
	CreatedBy pgtype.UUID
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.IsGroup, arg.Title, arg.CreatedBy)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.IsGroup,
		&i.Title,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations
WHERE id = $1
`

func (q *Queries) DeleteConversation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversation, id)
	return err
}

const getConversation = `-- name: GetConversation :one
SELECT id, is_group, title, created_by, created_at FROM conversations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetConversation(ctx context.Context, id pgtype.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.IsGroup,
		&i.Title,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationByIdWithCreator = `-- name: GetConversationByIdWithCreator :one
SELECT c.id, c.is_group, c.title, c.created_by, c.created_at, u.phone_number as creator_phone, u.display_name as creator_name
FROM conversations c
LEFT JOIN users u ON c.created_by = u.id
WHERE c.id = $1 LIMIT 1
`

type GetConversationByIdWithCreatorRow struct {
	ID           pgtype.UUID
	IsGroup      bool
	Title        pgtype.Text
	CreatedBy    pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	CreatorPhone pgtype.Text
	CreatorName  pgtype.Text
}

func (q *Queries) GetConversationByIdWithCreator(ctx context.Context, id pgtype.UUID) (GetConversationByIdWithCreatorRow, error) {
	row := q.db.QueryRow(ctx, getConversationByIdWithCreator, id)
	var i GetConversationByIdWithCreatorRow
	err := row.Scan(
		&i.ID,
		&i.IsGroup,
		&i.Title,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CreatorPhone,
		&i.CreatorName,
	)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT id, is_group, title, created_by, created_at FROM conversations
ORDER BY created_at DESC
`

func (q *Queries) ListConversations(ctx context.Context) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.IsGroup,
			&i.Title,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsByCreator = `-- name: ListConversationsByCreator :many
SELECT id, is_group, title, created_by, created_at FROM conversations
WHERE created_by = $1
ORDER BY created_at DESC
`

func (q *Queries) ListConversationsByCreator(ctx context.Context, createdBy pgtype.UUID) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversationsByCreator, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.IsGroup,
			&i.Title,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupConversations = `-- name: ListGroupConversations :many
SELECT id, is_group, title, created_by, created_at FROM conversations
WHERE is_group = true
ORDER BY created_at DESC
`

func (q *Queries) ListGroupConversations(ctx context.Context) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listGroupConversations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.IsGroup,
			&i.Title,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchConversationsByTitle = `-- name: SearchConversationsByTitle :many
SELECT id, is_group, title, created_by, created_at FROM conversations
WHERE title ILIKE '%' || $1 || '%'
ORDER BY created_at DESC
LIMIT 20
`

func (q *Queries) SearchConversationsByTitle(ctx context.Context, dollar_1 pgtype.Text) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, searchConversationsByTitle, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.IsGroup,
			&i.Title,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversation = `-- name: UpdateConversation :one
UPDATE conversations
SET title = $2
WHERE id = $1
RETURNING id, is_group, title, created_by, created_at
`

type UpdateConversationParams struct {
	ID    pgtype.UUID
	Title pgtype.Text
}

func (q *Queries) UpdateConversation(ctx context.Context, arg UpdateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, updateConversation, arg.ID, arg.Title)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.IsGroup,
		&i.Title,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const updateConversationTitle = `-- name: UpdateConversationTitle :one
UPDATE conversations
SET title = $2
WHERE id = $1
RETURNING id, is_group, title, created_by, created_at
`

type UpdateConversationTitleParams struct {
	ID    pgtype.UUID
	Title pgtype.Text
}

func (q *Queries) UpdateConversationTitle(ctx context.Context, arg UpdateConversationTitleParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, updateConversationTitle, arg.ID, arg.Title)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.IsGroup,
		&i.Title,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
