// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMediaByMessage = `-- name: CountMediaByMessage :one
SELECT COUNT(*) FROM media
WHERE message_id = $1
`

func (q *Queries) CountMediaByMessage(ctx context.Context, messageID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMediaByMessage, messageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (
  message_id, file_url, mime_type, file_size
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, message_id, file_url, mime_type, file_size, uploaded_at
`

type CreateMediaParams struct {
	MessageID pgtype.UUID
	FileUrl   string
	MimeType  string
	FileSize  pgtype.Int8
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.MessageID,
		arg.FileUrl,
		arg.MimeType,
		arg.FileSize,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.FileUrl,
		&i.MimeType,
		&i.FileSize,
		&i.UploadedAt,
	)
	return i, err
}

const deleteMedia = `-- name: DeleteMedia :exec
DELETE FROM media
WHERE id = $1
`

func (q *Queries) DeleteMedia(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMedia, id)
	return err
}

const deleteMediaByMessage = `-- name: DeleteMediaByMessage :exec
DELETE FROM media
WHERE message_id = $1
`

func (q *Queries) DeleteMediaByMessage(ctx context.Context, messageID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMediaByMessage, messageID)
	return err
}

const getMedia = `-- name: GetMedia :one
SELECT id, message_id, file_url, mime_type, file_size, uploaded_at FROM media
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMedia(ctx context.Context, id pgtype.UUID) (Medium, error) {
	row := q.db.QueryRow(ctx, getMedia, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.FileUrl,
		&i.MimeType,
		&i.FileSize,
		&i.UploadedAt,
	)
	return i, err
}

const getMediaByFileUrl = `-- name: GetMediaByFileUrl :one
SELECT id, message_id, file_url, mime_type, file_size, uploaded_at FROM media
WHERE file_url = $1 LIMIT 1
`

func (q *Queries) GetMediaByFileUrl(ctx context.Context, fileUrl string) (Medium, error) {
	row := q.db.QueryRow(ctx, getMediaByFileUrl, fileUrl)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.FileUrl,
		&i.MimeType,
		&i.FileSize,
		&i.UploadedAt,
	)
	return i, err
}

const getMediaByMessage = `-- name: GetMediaByMessage :many
SELECT id, message_id, file_url, mime_type, file_size, uploaded_at FROM media
WHERE message_id = $1
`

func (q *Queries) GetMediaByMessage(ctx context.Context, messageID pgtype.UUID) ([]Medium, error) {
	rows, err := q.db.Query(ctx, getMediaByMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.FileUrl,
			&i.MimeType,
			&i.FileSize,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMediaSizeByMessage = `-- name: GetMediaSizeByMessage :one
SELECT COALESCE(SUM(file_size), 0) FROM media
WHERE message_id = $1
`

func (q *Queries) GetMediaSizeByMessage(ctx context.Context, messageID pgtype.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getMediaSizeByMessage, messageID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getTotalMediaSize = `-- name: GetTotalMediaSize :one
SELECT COALESCE(SUM(file_size), 0) FROM media
`

func (q *Queries) GetTotalMediaSize(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, getTotalMediaSize)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const listMedia = `-- name: ListMedia :many
SELECT id, message_id, file_url, mime_type, file_size, uploaded_at FROM media
ORDER BY uploaded_at DESC
LIMIT $1 OFFSET $2
`

type ListMediaParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListMedia(ctx context.Context, arg ListMediaParams) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listMedia, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.FileUrl,
			&i.MimeType,
			&i.FileSize,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaByMimeType = `-- name: ListMediaByMimeType :many
SELECT id, message_id, file_url, mime_type, file_size, uploaded_at FROM media
WHERE mime_type = $1
ORDER BY uploaded_at DESC
`

func (q *Queries) ListMediaByMimeType(ctx context.Context, mimeType string) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listMediaByMimeType, mimeType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.FileUrl,
			&i.MimeType,
			&i.FileSize,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaByMimeTypePrefix = `-- name: ListMediaByMimeTypePrefix :many
SELECT id, message_id, file_url, mime_type, file_size, uploaded_at FROM media
WHERE mime_type LIKE $1 || '%'
ORDER BY uploaded_at DESC
`

func (q *Queries) ListMediaByMimeTypePrefix(ctx context.Context, dollar_1 pgtype.Text) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listMediaByMimeTypePrefix, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.FileUrl,
			&i.MimeType,
			&i.FileSize,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaBySizeRange = `-- name: ListMediaBySizeRange :many
SELECT id, message_id, file_url, mime_type, file_size, uploaded_at FROM media
WHERE file_size >= $1 AND file_size <= $2
ORDER BY file_size ASC
`

type ListMediaBySizeRangeParams struct {
	FileSize   pgtype.Int8
	FileSize_2 pgtype.Int8
}

func (q *Queries) ListMediaBySizeRange(ctx context.Context, arg ListMediaBySizeRangeParams) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listMediaBySizeRange, arg.FileSize, arg.FileSize_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.FileUrl,
			&i.MimeType,
			&i.FileSize,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaByUploadTimeRange = `-- name: ListMediaByUploadTimeRange :many
SELECT id, message_id, file_url, mime_type, file_size, uploaded_at FROM media
WHERE uploaded_at >= $1 AND uploaded_at <= $2
ORDER BY uploaded_at DESC
`

type ListMediaByUploadTimeRangeParams struct {
	UploadedAt   pgtype.Timestamptz
	UploadedAt_2 pgtype.Timestamptz
}

func (q *Queries) ListMediaByUploadTimeRange(ctx context.Context, arg ListMediaByUploadTimeRangeParams) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listMediaByUploadTimeRange, arg.UploadedAt, arg.UploadedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.FileUrl,
			&i.MimeType,
			&i.FileSize,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMediaFileInfo = `-- name: UpdateMediaFileInfo :one
UPDATE media
SET file_url = $2,
    file_size = $3
WHERE id = $1
RETURNING id, message_id, file_url, mime_type, file_size, uploaded_at
`

type UpdateMediaFileInfoParams struct {
	ID       pgtype.UUID
	FileUrl  string
	FileSize pgtype.Int8
}

func (q *Queries) UpdateMediaFileInfo(ctx context.Context, arg UpdateMediaFileInfoParams) (Medium, error) {
	row := q.db.QueryRow(ctx, updateMediaFileInfo, arg.ID, arg.FileUrl, arg.FileSize)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.FileUrl,
		&i.MimeType,
		&i.FileSize,
		&i.UploadedAt,
	)
	return i, err
}
