// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Contact struct {
	UserID      pgtype.UUID
	ContactID   pgtype.UUID
	ContactName pgtype.Text
}

type Conversation struct {
	ID        pgtype.UUID
	IsGroup   bool
	Title     pgtype.Text
	CreatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type ConversationParticipant struct {
	ConversationID pgtype.UUID
	UserID         pgtype.UUID
	Role           pgtype.Text
	JoinedAt       pgtype.Timestamptz
}

type EncryptionKey struct {
	DeviceID        pgtype.UUID
	IdentityKey     string
	PrekeyPublic    string
	PrekeySignature string
}

type Medium struct {
	ID         pgtype.UUID
	MessageID  pgtype.UUID
	FileUrl    string
	MimeType   string
	FileSize   pgtype.Int8
	UploadedAt pgtype.Timestamptz
}

type Message struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	SenderID       pgtype.UUID
	Content        pgtype.Text
	MessageType    string
	ReplyToID      pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

type MessageReaction struct {
	MessageID pgtype.UUID
	UserID    pgtype.UUID
	Reaction  string
	ReactedAt pgtype.Timestamptz
}

type MessageReceipt struct {
	MessageID   pgtype.UUID
	UserID      pgtype.UUID
	DeliveredAt pgtype.Timestamptz
	ReadAt      pgtype.Timestamptz
}

type User struct {
	ID          pgtype.UUID
	PhoneNumber string
	DisplayName pgtype.Text
	About       pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type UserDevice struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	DeviceName pgtype.Text
	DeviceType pgtype.Text
	PublicKey  string
	CreatedAt  pgtype.Timestamptz
}
