// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_devices.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUserDevices = `-- name: CountUserDevices :one
SELECT COUNT(*) FROM user_devices
WHERE user_id = $1
`

func (q *Queries) CountUserDevices(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserDevices, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserDevice = `-- name: CreateUserDevice :one
INSERT INTO user_devices (
  user_id, device_name, device_type, public_key
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, user_id, device_name, device_type, public_key, created_at
`

type CreateUserDeviceParams struct {
	UserID     pgtype.UUID
	DeviceName pgtype.Text
	DeviceType pgtype.Text
	PublicKey  string
}

func (q *Queries) CreateUserDevice(ctx context.Context, arg CreateUserDeviceParams) (UserDevice, error) {
	row := q.db.QueryRow(ctx, createUserDevice,
		arg.UserID,
		arg.DeviceName,
		arg.DeviceType,
		arg.PublicKey,
	)
	var i UserDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceName,
		&i.DeviceType,
		&i.PublicKey,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserDevice = `-- name: DeleteUserDevice :exec
DELETE FROM user_devices
WHERE id = $1
`

func (q *Queries) DeleteUserDevice(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserDevice, id)
	return err
}

const deleteUserDevicesByUser = `-- name: DeleteUserDevicesByUser :exec
DELETE FROM user_devices
WHERE user_id = $1
`

func (q *Queries) DeleteUserDevicesByUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserDevicesByUser, userID)
	return err
}

const getUserDevice = `-- name: GetUserDevice :one
SELECT id, user_id, device_name, device_type, public_key, created_at FROM user_devices
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserDevice(ctx context.Context, id pgtype.UUID) (UserDevice, error) {
	row := q.db.QueryRow(ctx, getUserDevice, id)
	var i UserDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceName,
		&i.DeviceType,
		&i.PublicKey,
		&i.CreatedAt,
	)
	return i, err
}

const getUserDeviceByUserAndKey = `-- name: GetUserDeviceByUserAndKey :one
SELECT id, user_id, device_name, device_type, public_key, created_at FROM user_devices
WHERE user_id = $1 AND public_key = $2 LIMIT 1
`

type GetUserDeviceByUserAndKeyParams struct {
	UserID    pgtype.UUID
	PublicKey string
}

func (q *Queries) GetUserDeviceByUserAndKey(ctx context.Context, arg GetUserDeviceByUserAndKeyParams) (UserDevice, error) {
	row := q.db.QueryRow(ctx, getUserDeviceByUserAndKey, arg.UserID, arg.PublicKey)
	var i UserDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceName,
		&i.DeviceType,
		&i.PublicKey,
		&i.CreatedAt,
	)
	return i, err
}

const listAllUserDevices = `-- name: ListAllUserDevices :many
SELECT ud.id, ud.user_id, ud.device_name, ud.device_type, ud.public_key, ud.created_at, u.phone_number, u.display_name
FROM user_devices ud
JOIN users u ON ud.user_id = u.id
ORDER BY ud.created_at DESC
`

type ListAllUserDevicesRow struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	DeviceName  pgtype.Text
	DeviceType  pgtype.Text
	PublicKey   string
	CreatedAt   pgtype.Timestamptz
	PhoneNumber string
	DisplayName pgtype.Text
}

func (q *Queries) ListAllUserDevices(ctx context.Context) ([]ListAllUserDevicesRow, error) {
	rows, err := q.db.Query(ctx, listAllUserDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllUserDevicesRow
	for rows.Next() {
		var i ListAllUserDevicesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceName,
			&i.DeviceType,
			&i.PublicKey,
			&i.CreatedAt,
			&i.PhoneNumber,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDevices = `-- name: ListUserDevices :many
SELECT id, user_id, device_name, device_type, public_key, created_at FROM user_devices
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUserDevices(ctx context.Context, userID pgtype.UUID) ([]UserDevice, error) {
	rows, err := q.db.Query(ctx, listUserDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserDevice
	for rows.Next() {
		var i UserDevice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceName,
			&i.DeviceType,
			&i.PublicKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserDevice = `-- name: UpdateUserDevice :one
UPDATE user_devices
SET device_name = $2,
    device_type = $3
WHERE id = $1
RETURNING id, user_id, device_name, device_type, public_key, created_at
`

type UpdateUserDeviceParams struct {
	ID         pgtype.UUID
	DeviceName pgtype.Text
	DeviceType pgtype.Text
}

func (q *Queries) UpdateUserDevice(ctx context.Context, arg UpdateUserDeviceParams) (UserDevice, error) {
	row := q.db.QueryRow(ctx, updateUserDevice, arg.ID, arg.DeviceName, arg.DeviceType)
	var i UserDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceName,
		&i.DeviceType,
		&i.PublicKey,
		&i.CreatedAt,
	)
	return i, err
}
