// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  phone_number, display_name, about
) VALUES (
  $1, $2, $3
)
RETURNING id, phone_number, display_name, about, created_at
`

type CreateUserParams struct {
	PhoneNumber string
	DisplayName pgtype.Text
	About       pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.PhoneNumber, arg.DisplayName, arg.About)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.DisplayName,
		&i.About,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, phone_number, display_name, about, created_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.DisplayName,
		&i.About,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByPhoneNumber = `-- name: GetUserByPhoneNumber :one
SELECT id, phone_number, display_name, about, created_at FROM users
WHERE phone_number = $1 LIMIT 1
`

func (q *Queries) GetUserByPhoneNumber(ctx context.Context, phoneNumber string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhoneNumber, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.DisplayName,
		&i.About,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, phone_number, display_name, about, created_at FROM users
ORDER BY display_name, phone_number
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.PhoneNumber,
			&i.DisplayName,
			&i.About,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersByDisplayName = `-- name: SearchUsersByDisplayName :many
SELECT id, phone_number, display_name, about, created_at FROM users
WHERE display_name ILIKE '%' || $1 || '%'
ORDER BY display_name
LIMIT 20
`

func (q *Queries) SearchUsersByDisplayName(ctx context.Context, dollar_1 pgtype.Text) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsersByDisplayName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.PhoneNumber,
			&i.DisplayName,
			&i.About,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersByPhone = `-- name: SearchUsersByPhone :many
SELECT id, phone_number, display_name, about, created_at FROM users
WHERE phone_number LIKE $1 || '%'
ORDER BY phone_number
LIMIT 20
`

func (q *Queries) SearchUsersByPhone(ctx context.Context, dollar_1 pgtype.Text) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsersByPhone, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.PhoneNumber,
			&i.DisplayName,
			&i.About,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET phone_number = $2,
    display_name = $3,
    about = $4
WHERE id = $1
RETURNING id, phone_number, display_name, about, created_at
`

type UpdateUserParams struct {
	ID          pgtype.UUID
	PhoneNumber string
	DisplayName pgtype.Text
	About       pgtype.Text
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.PhoneNumber,
		arg.DisplayName,
		arg.About,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.DisplayName,
		&i.About,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserAbout = `-- name: UpdateUserAbout :one
UPDATE users
SET about = $2
WHERE id = $1
RETURNING id, phone_number, display_name, about, created_at
`

type UpdateUserAboutParams struct {
	ID    pgtype.UUID
	About pgtype.Text
}

func (q *Queries) UpdateUserAbout(ctx context.Context, arg UpdateUserAboutParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserAbout, arg.ID, arg.About)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.DisplayName,
		&i.About,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :one
UPDATE users
SET display_name = $2
WHERE id = $1
RETURNING id, phone_number, display_name, about, created_at
`

type UpdateUserDisplayNameParams struct {
	ID          pgtype.UUID
	DisplayName pgtype.Text
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserDisplayName, arg.ID, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.DisplayName,
		&i.About,
		&i.CreatedAt,
	)
	return i, err
}
